-- Add leaderboard statistics columns to phase_teams table
ALTER TABLE phase_teams
ADD COLUMN played INTEGER DEFAULT 0,
ADD COLUMN wins INTEGER DEFAULT 0,
ADD COLUMN draws INTEGER DEFAULT 0,
ADD COLUMN losses INTEGER DEFAULT 0,
ADD COLUMN forfeits INTEGER DEFAULT 0,
ADD COLUMN score_for INTEGER DEFAULT 0,
ADD COLUMN score_against INTEGER DEFAULT 0,
ADD COLUMN differential INTEGER DEFAULT 0,
ADD COLUMN points INTEGER DEFAULT 0;
