name: Deploy Bot to Fly.io

on:
  push:
    branches:
      - main # Le déploiement se lance quand tu envoies sur la branche main
    paths:
      - 'bot/**' # 🎯 CRITIQUE : Ne se lance QUE si tu as modifié un fichier dans le dossier /bot

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy Bot
    runs-on: ubuntu-latest
    
    # On précise à GitHub de rentrer dans le dossier bot pour taper les commandes
    defaults:
      run:
        working-directory: ./bot 

    steps:
      - name: 📥 Téléchargement du code
        uses: actions/checkout@v4

      - name: 🛠️ Installation des outils Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: 🚀 Déploiement sur Fly.io
        run: flyctl deploy --remote-only